version: '3'

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    volumes:
      - namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - CORE_CONF_hadoop_proxyuser_hue_hosts=*
      - CORE_CONF_hadoop_proxyuser_hue_groups=*
      - HDFS_CONF_dfs_webhdfs_enable=true
      - HTTPFS_CONF_httpfs_proxyuser_hue_hosts=*
      - HTTPFS_CONF_httpfs_proxyuser_hue_groups=*
    ports:
      - "9870:9870"

  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode1
    volumes:
      - /mnt/datanode1:/hadoop/dfs/data
    environment:
      - SERVICE_PRECONDITION=namenode:9870
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - CORE_CONF_hadoop_proxyuser_hue_hosts=*
      - CORE_CONF_hadoop_proxyuser_hue_groups=*
      - HDFS_CONF_dfs_webhdfs_enable=true
      - HTTPFS_CONF_httpfs_proxyuser_hue_hosts=*
      - HTTPFS_CONF_httpfs_proxyuser_hue_groups=*
    links:
      - namenode

  datanode2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode2
    volumes:
      - /mnt/datanode2:/hadoop/dfs/data
    environment:
      - SERVICE_PRECONDITION=namenode:9870
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - CORE_CONF_hadoop_proxyuser_hue_hosts=*
      - CORE_CONF_hadoop_proxyuser_hue_groups=*
      - HDFS_CONF_dfs_webhdfs_enable=true
      - HTTPFS_CONF_httpfs_proxyuser_hue_hosts=*
      - HTTPFS_CONF_httpfs_proxyuser_hue_groups=*
    links:
      - namenode

  datanode3:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode3
    volumes:
      - /mnt/datanode3:/hadoop/dfs/data
    environment:
      - SERVICE_PRECONDITION=namenode:9870
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - CORE_CONF_hadoop_proxyuser_hue_hosts=*
      - CORE_CONF_hadoop_proxyuser_hue_groups=*
      - HDFS_CONF_dfs_webhdfs_enable=true
      - HTTPFS_CONF_httpfs_proxyuser_hue_hosts=*
      - HTTPFS_CONF_httpfs_proxyuser_hue_groups=*
    links:
      - namenode

  datanode4:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode4
    volumes:
      - /mnt/datanode4:/hadoop/dfs/data
    environment:
      - SERVICE_PRECONDITION=namenode:9870
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - CORE_CONF_hadoop_proxyuser_hue_hosts=*
      - CORE_CONF_hadoop_proxyuser_hue_groups=*
      - HDFS_CONF_dfs_webhdfs_enable=true
      - HTTPFS_CONF_httpfs_proxyuser_hue_hosts=*
      - HTTPFS_CONF_httpfs_proxyuser_hue_groups=*
    links:
      - namenode

  datanode5:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode5
    volumes:
      - /mnt/datanode5:/hadoop/dfs/data
    environment:
      - SERVICE_PRECONDITION=namenode:9870
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - CORE_CONF_hadoop_proxyuser_hue_hosts=*
      - CORE_CONF_hadoop_proxyuser_hue_groups=*
      - HDFS_CONF_dfs_webhdfs_enable=true
      - HTTPFS_CONF_httpfs_proxyuser_hue_hosts=*
      - HTTPFS_CONF_httpfs_proxyuser_hue_groups=*
    links:
      - namenode

  hue:
    image: gethue/hue:latest
    container_name: hue
    ports:
      - "8888:8888"
    volumes:
      - ./hue.ini:/usr/share/hue/desktop/conf/hue.ini
    environment:
      - HUE_DATABASE_ENGINE=sqlite
      - HUE_DATABASE_NAME=/hue/desktop.db
    links:
      - namenode
      - datanode1
      - datanode2
      - datanode3
      - datanode4
      - datanode5
    depends_on:
      - namenode
      - datanode1
      - datanode2
      - datanode3
      - datanode4
      - datanode5

volumes:
  namenode:

